// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PartialFoods.Services.OrderManagementServer.Entities;
using System;

namespace PartialFoods.Services.OrderManagementServer.Migrations
{
    [DbContext(typeof(OrdersContext))]
    [Migration("20171015152351_RenameActivityToActivityType")]
    partial class RenameActivityToActivityType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("PartialFoods.Services.OrderManagementServer.Entities.LineItem", b =>
                {
                    b.Property<string>("OrderID");

                    b.Property<string>("SKU");

                    b.Property<int>("Quantity");

                    b.Property<int>("UnitPrice");

                    b.HasKey("OrderID", "SKU");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PartialFoods.Services.OrderManagementServer.Entities.Order", b =>
                {
                    b.Property<string>("OrderID")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CreatedOn");

                    b.Property<int>("TaxRate");

                    b.Property<string>("UserID");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PartialFoods.Services.OrderManagementServer.Entities.OrderActivity", b =>
                {
                    b.Property<string>("OrderID");

                    b.Property<string>("ActivityID");

                    b.Property<int>("ActivityType");

                    b.Property<long>("OccuredOn");

                    b.Property<string>("UserID");

                    b.HasKey("OrderID", "ActivityID");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("PartialFoods.Services.OrderManagementServer.Entities.LineItem", b =>
                {
                    b.HasOne("PartialFoods.Services.OrderManagementServer.Entities.Order")
                        .WithMany("LineItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PartialFoods.Services.OrderManagementServer.Entities.OrderActivity", b =>
                {
                    b.HasOne("PartialFoods.Services.OrderManagementServer.Entities.Order")
                        .WithMany("Activities")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
