// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ordermgmt.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace PartialFoods.Services {
  public static partial class OrderManagement
  {
    static readonly string __ServiceName = "PartialFoods.Services.OrderManagement";

    static readonly grpc::Marshaller<global::PartialFoods.Services.GetOrderRequest> __Marshaller_GetOrderRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PartialFoods.Services.GetOrderRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::PartialFoods.Services.GetOrderResponse> __Marshaller_GetOrderResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PartialFoods.Services.GetOrderResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::PartialFoods.Services.OrderExistsResponse> __Marshaller_OrderExistsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PartialFoods.Services.OrderExistsResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::PartialFoods.Services.GetOrderRequest, global::PartialFoods.Services.GetOrderResponse> __Method_GetOrder = new grpc::Method<global::PartialFoods.Services.GetOrderRequest, global::PartialFoods.Services.GetOrderResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOrder",
        __Marshaller_GetOrderRequest,
        __Marshaller_GetOrderResponse);

    static readonly grpc::Method<global::PartialFoods.Services.GetOrderRequest, global::PartialFoods.Services.OrderExistsResponse> __Method_OrderExists = new grpc::Method<global::PartialFoods.Services.GetOrderRequest, global::PartialFoods.Services.OrderExistsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "OrderExists",
        __Marshaller_GetOrderRequest,
        __Marshaller_OrderExistsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::PartialFoods.Services.OrdermgmtReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of OrderManagement</summary>
    public abstract partial class OrderManagementBase
    {
      public virtual global::System.Threading.Tasks.Task<global::PartialFoods.Services.GetOrderResponse> GetOrder(global::PartialFoods.Services.GetOrderRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::PartialFoods.Services.OrderExistsResponse> OrderExists(global::PartialFoods.Services.GetOrderRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for OrderManagement</summary>
    public partial class OrderManagementClient : grpc::ClientBase<OrderManagementClient>
    {
      /// <summary>Creates a new client for OrderManagement</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public OrderManagementClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for OrderManagement that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public OrderManagementClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected OrderManagementClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected OrderManagementClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::PartialFoods.Services.GetOrderResponse GetOrder(global::PartialFoods.Services.GetOrderRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOrder(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PartialFoods.Services.GetOrderResponse GetOrder(global::PartialFoods.Services.GetOrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOrder, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PartialFoods.Services.GetOrderResponse> GetOrderAsync(global::PartialFoods.Services.GetOrderRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOrderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PartialFoods.Services.GetOrderResponse> GetOrderAsync(global::PartialFoods.Services.GetOrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOrder, null, options, request);
      }
      public virtual global::PartialFoods.Services.OrderExistsResponse OrderExists(global::PartialFoods.Services.GetOrderRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return OrderExists(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PartialFoods.Services.OrderExistsResponse OrderExists(global::PartialFoods.Services.GetOrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_OrderExists, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PartialFoods.Services.OrderExistsResponse> OrderExistsAsync(global::PartialFoods.Services.GetOrderRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return OrderExistsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PartialFoods.Services.OrderExistsResponse> OrderExistsAsync(global::PartialFoods.Services.GetOrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_OrderExists, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override OrderManagementClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new OrderManagementClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(OrderManagementBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetOrder, serviceImpl.GetOrder)
          .AddMethod(__Method_OrderExists, serviceImpl.OrderExists).Build();
    }

  }
}
#endregion
